### ISSUE TITLE
Give Sync all option

### ISSUE THREAD

**Issue by justkorix** [trakt-tools/universal-trakt-scrobbler#264] opened 2023-01-18 22:38 UTC
So I think what might be a great improvement here would be the ability to do a "Sync All" option where it automatically grabs the release from history and matches to Trakt without the need for a toggle and waiting for my YEARS of Netflix history to populate. Maybe just after a first install or if no syncs have been done.

**Comment by rafaelgomesxyz** [comment] 2023-07-01 13:07
Closing as duplicate of #47

**Closed as not planned by rafaelgomesxyz** 2023-07-01 13:07 UTC
Labels: duplicate
