### ISSUE TITLE
No Releases available after PRs were merged

### ISSUE THREAD

**Issue by downey-lv** [trakt-tools/universal-trakt-scrobbler#248] opened 2023-01-06 13:35 UTC
There are no Releases available to download. I assume it is related to today's merge of PRs? @MrMamen 

https://github.com/trakt-tools/universal-trakt-scrobbler/releases
![image](https://user-images.githubusercontent.com/4418470/211017794-58cb685e-4e4d-4ab5-9f4a-e0411aabdfd1.png)

_Originally posted by @VapidLinus in https://github.com/trakt-tools/universal-trakt-scrobbler/issues/237#issuecomment-1373595095_

**Comment by MrMamen** [comment] 2023-01-06 13:44
I have no idea why it was only created as a draft, but I manually published a new release now. @rafaelgomesxyz has to look into @trakt-tools-bot if it works as intended.

**Comment by downey-lv** [comment] 2023-01-09 10:45
Seems to have happened again, please post the newest release @MrMamen @rafaelgomesxyz

**Comment by MrMamen** [comment] 2023-01-09 10:50
Done. I'll do my best to remember to manually create release after a merge.

**Comment by MrMamen** [comment] 2023-02-01 18:43
This should be the highest priority @rafaelgomesxyz

**Comment by Kellett** [comment] 2023-02-13 14:41
The version on the FireFox store is pretty out of date (Last updated: 2 months ago (Dec 10, 2022)). Is this related?

**Comment by rafaelgomesxyz** [comment] 2023-03-07 01:13
I don't really know why it was being created as a draft, maybe it does that after uploading assets? Because the process was:

> create release -> upload assets

So maybe that was the issue. Regardless, I've changed it to:

> create release -> upload assets -> update release to ensure it's not a draft

So it should be fixed.

**Comment by rafaelgomesxyz** [comment] 2023-03-07 01:13
The Firefox version has been updated as well.

**Closed as completed by rafaelgomesxyz** 2023-03-07 01:13 UTC
Labels: bug
