### ISSUE TITLE
Trakt and Netflix and Universal Trakt Scrobbler

### ISSUE THREAD

**Issue by xoxo64** [trakt-tools/universal-trakt-scrobbler#297] opened 2023-04-04 17:12 UTC
Hi. I am trying to use this program in Netflix in Firefox. I am getting an error message - "Oath Error. The requested redirect uri is malformed or doesn't match client redirect URI"

**Comment by rafaelgomesxyz** [comment] 2023-04-04 19:00
Closing as duplicate of #293

**Closed as not planned by rafaelgomesxyz** 2023-04-04 19:00 UTC
Labels: duplicate
