### ISSUE TITLE
Cannot Sync to Prime, Netflix, HBO

### ISSUE THREAD

**Issue by Brandon1212b** [trakt-tools/universal-trakt-scrobbler#179] opened 2022-08-23 16:02 UTC
I am logged into the services however when I click sync I get the following error message: "Not Logged In
Looks like you're not logged in to this service. Please go to the page below and log in before trying to sync."

When clicking the hyperlink for the page it shows that I am logged in.

**Comment by MrMamen** [comment] 2022-08-29 13:56
There are issues with Prime and HBO. However Netflix should work, and it works for me. What region are you in?

**Comment by eduardogd** [comment] 2022-09-07 17:45
Same issue here with amazon prime and hbo+. I'm from Brazil.

**Comment by Trigger911** [comment] 2022-09-13 18:07
Can confirm Prime is not working. I am in the USA.. Thanks for your hard work :)

**Comment by mrzoops** [comment] 2022-09-20 18:45
This seems to be because the extension is looking for primevideo.com to authenticate which has changed to a different URL. Same for HBO max.

**Comment by rafaelgomesxyz** [comment] 2022-10-01 19:11
Please follow #99 for Amazon Prime issues and #133 for HBO Max issues. Closing as duplicate of those.

Netflix should work, please try with the latest beta version.

**Closed as completed by rafaelgomesxyz** 2022-10-01 19:11 UTC
Labels: duplicate
