### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by gpmnsp** [trakt-tools/universal-trakt-scrobbler#124] opened 2022-02-28 19:08 UTC
I'd like to add this to my FF.
There seem to be zero instructions how to do this.
And no, I am not a 'developer'- is this a requirement, though?
Just wondering. Any help appreciated.
PS: The FF addon button leads to nowhere (404)

**Comment by BartekDobrowolskiNowakowskiTR** [comment] 2022-02-28 21:26
Try following https://github.com/trakt-tools/universal-trakt-scrobbler/issues/114

**Comment by Starminder** [comment] 2022-02-28 21:29
You just pointed #114 to #124, and #124 back to #114.  :/

**Comment by gpmnsp** [comment] 2022-02-28 22:41
@Starminder 
Yes. It's so and it's a pity.
I don't get it why  someone serious would do such a thing.
Not a way to promote. in my thinkin.

**Comment by rafaelgomesxyz** [comment] 2022-02-28 23:09
Hi. I was holding out on releasing it because I wanted to do some changes first, but I've been quite busy lately, so I haven't had the time. But I decided to just release it and do those changes later.

I've sent the app for review. Once it's approved, I'll release it in the Chrome and Firefox stores. Hopefully that happens before the end of the week.

**Comment by rafaelgomesxyz** [comment] 2022-03-07 01:48
Closing as duplicate of #61.

You can now download the built zip file for the extension and load it manually from here: https://github.com/trakt-tools/universal-trakt-scrobbler/releases/tag/1.0.0-beta

I'm waiting for the extension to be approved to upload it to the Chrome and Firefox stores.

**Closed as completed by rafaelgomesxyz** 2022-03-07 01:48 UTC
Labels: duplicate
