### ISSUE TITLE
Syncing not working for HBO Max and Amazon Primevideo

### ISSUE THREAD

**Issue by Manfred73** [trakt-tools/universal-trakt-scrobbler#177] opened 2022-08-04 19:26 UTC
I'm able to sync with Netflix after logging into my Netflix account.
Syncing however doesn't work with HBO Max and Amazon Primevideo. It comes with a popup to login and then sync again. Even after logging into my HBO Max and Primevideo account, syncing still doesn't work. It keeps popping up with the message I need to login.

**Comment by netcaretx** [comment] 2022-08-08 20:55
same here USA

**Comment by Brandon1212b** [comment] 2022-08-23 16:02
Same here

**Comment by Brandon1212b** [comment] 2022-08-23 16:14
Problem is because HBO is redirected to Hbomax.com which automatically does not have the user logged in.

Directing to https://play.hbomax.com/page/urn:hbo:page:home might fix this

**Comment by pphillips-sf** [comment] 2022-08-31 23:06
I am having similar issue with Prime Video, as the universal scrobbler shows it seems to want to see "primevideo.com", and complains that it is not logged in, but my account force redirects to Amazon.com to watch video.  I am in the USA, not on any VPNs.

**Comment by KidAperture** [comment] 2022-09-02 19:21
Same here, both sites in the US do not sync.

**Comment by mrzoops** [comment] 2022-09-22 13:30
Is this configured in come config file we can edit?

**Comment by rafaelgomesxyz** [comment] 2022-10-01 19:11
Please follow #99 for Amazon Prime issues and #133 for HBO Max issues. Closing as duplicate of those.

**Closed as completed by rafaelgomesxyz** 2022-10-01 19:11 UTC
Labels: duplicate
